name: fallback

director_uuid: 879402dd-f9f8-4463-9f05-xxxxxxxxxx

releases:
- name: dummy
  version: latest
- name: syslog-release
  version: latest

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

update:
  canaries: 10
  max_in_flight: 10
  canary_watch_time: 30000-600000
  update_watch_time: 5000-600000
  serial: false

instance_groups:
- name: dummy_with_package
  azs: [z1]
  jobs:
  - name: dummy_with_package
    release: dummy
  - name: syslog_forwarder
    release: syslog-release
  instances: 2
  vm_type: default
  stemcell: default
  networks:
  - name: default
  properties:
    address: 10.10.0.102
    port: 514
    transport: tcp
    fallback_addresses:
    - address: 10.10.0.103
      port: 514
      transport: tcp

- name: syslog_storer_primary
  azs: [z1]
  jobs:
  - name: syslog_storer
    release: syslog-release
  instances: 1
  vm_type: default
  stemcell: default
  networks:
  - name: default
    static_ips: [10.10.0.102]
  properties:
    transport: tcp

- name: syslog_storer_fallback
  azs: [z1]
  jobs:
  - name: syslog_storer
    release: syslog-release
  instances: 1
  vm_type: default
  stemcell: default
  networks:
  - name: default
    static_ips: [10.10.0.103]
  properties:
    transport: tcp
