---
name: input-output

director_uuid: DIRECTOR_UUID

stemcells:
  - name: bosh-warden-boshlite-ubuntu-trusty-go_agent
    alias: ubuntu
    version: latest
releases:
  - name: syslog-release
    version: latest

instance_groups:
  - name: syslog_forwarder
    jobs: 
    - name: syslog_forwarder
      release: syslog-release
    instances: 1
    stemcell: ubuntu
    azs: [z1]
    vm_type: default
    networks:
      - name: default
        static_ips: [10.244.0.34]

  - name: syslog_storer
    jobs: 
    - name: syslog_storer
      release: syslog-release
      properties:
        port: 24173
        transport: relp
    instances: 1
    stemcell: ubuntu
    azs: [z1]
    vm_type: default
    networks:
      - name: default
        static_ips: [10.244.0.35]

properties:
  warden:
    kernel_network_tuning_enabled: true

update:
  canaries: 1
  max_in_flight: 3
  canary_watch_time: 30000-600000
  update_watch_time: 5000-600000
